name: IridiumCTF
author: skyphi
version: 1.4
api-version: 1.21
main: dev.skyphi.IridiumCTF
depend: [ProtocolLib]
commands:
  iridiumctf:
    description: Main IridiumCTF command
    usage: /<command> <number>
    default: op
    aliases: [ctf]
  score:
    description: Get the current game's score
    usage: /<command>